name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch (e.g., main or master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # Use a stable Node.js version

      - name: Install dependencies (if any)
        run: |
          npm install  # Add this if you have a package.json file

      - name: Build project (if any)
        run: |
          npm run build  # Add this if you have a build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Change this if your files are in a subdirectory (e.g., ./dist)